---
abstract: 'efficient shared mutable hash'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Errno: 1.00
  ExtUtils::CBuilder: 0.15
  File::Temp: 0.22
  Module::Build: 0
  POSIX: 0
  Test::More: 0
  perl: 5.014
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.014
  strict: 0
  warnings: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-SharedMem
provides:
  Hash::SharedMem:
    file: lib/Hash/SharedMem.pm
  Hash::SharedMem::Handle:
    file: lib/Hash/SharedMem/Handle.pm
requires:
  Exporter: 0
  XSLoader: 0
  parent: 0
  perl: 5.014
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.000
